const PDFDocument = require('pdfkit');

const generateTransactionPDF = async (transactions, type, startDate, endDate) => {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({ 
        margin: 50,
        size: 'A4'
      });
      
      const buffers = [];
      
      doc.on('data', buffers.push.bind(buffers));
      doc.on('end', () => {
        const pdfData = Buffer.concat(buffers);
        resolve(pdfData);
      });
      
      // Header with orange background
      doc.fillColor('#FF5722')  // Deep Orange color
         .rect(0, 0, doc.page.width, 120)
         .fill();
      
      // Company Name
      doc.fillColor('white')
         .fontSize(24)
         .font('Helvetica-Bold')
         .text('SHAHFARID REAL ESTATE COMPANY', {
           align: 'center',
           y: 40
         });
      
      // Address
      doc.fontSize(12)
         .font('Helvetica')
         .text('Ambika Sarak, Jhiltuli, Faridpur', {
           align: 'center',
           y: 70
         });
      
      // Report Title
      doc.fillColor('black')
         .fontSize(18)
         .font('Helvetica-Bold')
         .text(`${type.toUpperCase()} TRANSACTIONS REPORT`, {
           align: 'center',
           y: 140
         });
      
      // Date Range
      doc.fontSize(10)
         .font('Helvetica')
         .text(`Period: ${new Date(startDate).toLocaleDateString()} to ${new Date(endDate).toLocaleDateString()}`, {
           align: 'center',
           y: 170
         });
      
      // Table Header
      const tableTop = 200;
      
      doc.fontSize(10)
         .font('Helvetica-Bold')
         .text('Voucher No', 50, tableTop)
         .text('Date', 150, tableTop)
         .text('Name', 220, tableTop)
         .text('Description', 350, tableTop)
         .text('Amount (৳)', 500, tableTop, { align: 'right' });
      
      // Line under header
      doc.moveTo(50, tableTop + 15)
         .lineTo(550, tableTop + 15)
         .lineWidth(1)
         .stroke();
      
      // Table Rows
      let y = tableTop + 30;
      let total = 0;
      let serial = 1;
      
      doc.fontSize(9).font('Helvetica');
      
      transactions.forEach(transaction => {
        // Check if we need a new page
        if (y > 700) {
          doc.addPage();
          y = 50;
          
          // Add header on new page
          doc.fillColor('#FF5722')
             .rect(0, 0, doc.page.width, 50)
             .fill();
          
          doc.fillColor('white')
             .fontSize(14)
             .font('Helvetica-Bold')
             .text('SHAHFARID REAL ESTATE COMPANY - Continued', {
               align: 'center',
               y: 20
             });
          
          y += 30;
        }
        
        // Voucher Number
        doc.text(transaction.voucher_number || 'N/A', 50, y);
        
        // Date
        doc.text(new Date(transaction.date).toLocaleDateString(), 150, y);
        
        // Name
        const name = transaction.name || '';
        const shortName = name.length > 20 ? name.substring(0, 20) + '...' : name;
        doc.text(shortName, 220, y, { width: 120 });
        
        // Description
        const description = transaction.description || '';
        const shortDesc = description.length > 30 ? description.substring(0, 30) + '...' : description;
        doc.text(shortDesc, 350, y, { width: 140 });
        
        // Amount
        const amount = parseFloat(transaction.amount || 0);
        doc.text('৳' + amount.toLocaleString('en-IN'), 500, y, { align: 'right' });
        
        total += amount;
        serial++;
        y += 20;
      });
      
      // Total Line
      doc.moveTo(50, y + 5)
         .lineTo(550, y + 5)
         .lineWidth(1)
         .stroke();
      
      // Total Amount
      doc.fontSize(10)
         .font('Helvetica-Bold')
         .text('TOTAL', 350, y + 15)
         .text('৳' + total.toLocaleString('en-IN'), 500, y + 15, { align: 'right' });
      
      // Footer
      const footerY = doc.page.height - 50;
      
      doc.fontSize(8)
         .fillColor('gray')
         .font('Helvetica')
         .text('Generated by SHAHFARID REAL ESTATE COMPANY - Accounts Management System', 
               50, footerY, { align: 'center' });
      
      doc.text(`Generated on: ${new Date().toLocaleDateString()}`, 
               50, footerY + 15, { align: 'center' });
      
      doc.end();
    } catch (error) {
      console.error('PDF Generation Error:', error);
      reject(error);
    }
  });
};

module.exports = { 
  generateTransactionPDF
};